messages:
    error:
        nocommand: "&9Error> &7That is not a valid command"
        invalidargs: "&9Error> &7Invalid command arguments"
        cannotexecute: "&9Error> &7You cannot execute that command"
        invalidplayer: "&9Error> &7That player does not exist"
        nopermission: "&9Error> &7You do not have permission to execute that command"
    guild:
        chunkclaimed: "&9Guilds> &7You have claimed this chunk"
        chunkunclaimed: "&9Guilds> &7You have unclaimed this chunk"
        error:
            noinvite: "&9Guilds> &7You do not have an invite for that guild"
            invalidname: "&9Guilds> &7Guild names must be alphanumeric and less than 12 characters"
            hasinvite: "&9Guilds> &7You've already sent an invite to that player"
            inguild: "&9Guilds> &7You are already in a guild"
            notinguild: "&9Guilds> &7You have to be in a guild to use this command"
            invalidguild: "&9Guilds> &7That is no longer a valid guild"
            lowrole: "&9Guilds> &7Your role is not high enough to use this command"
            maxclaims: "&9Guilds> &7You have reached your guilds max amount of claims"
            leaderleave: "&9Guilds> &7You must promote an admin to leader before leaving"
            notownchunk: "&9Guilds> &7You do not own this chunk!"
            notenoughfunds: "&9Guilds> &7You lack the funds to create a guild"
            inviteotherteam: "&9Guilds> &7You cannot invite a player from a different team"
            joinotherteam: "&9Guilds> &7You cannot join a guild apart of a different team"
            kickself: "&9Guilds> &7You cannot kick yourself"
            inviteself: "&9Guilds> &7You cannot invite yourself"
            inviteplayeringuild: "&9Guilds> &7You cannot invite a player who is in a guild"
            claimingclaimedchunk: "&9Guilds> &7You cannot claim land that is already claimed"
            claimtoofast: "&9Guilds> &7You cannot claim this land because it was claimed recently"
            promoteself: "&9Guilds> &7You cannot promote yourself"
            demoteself: "&9Guilds> &7You cannot demote yourself"
            demotemember: "&9Guilds> &7You cannot demote a member"
            nohomeset: "&9Guilds> &7Your guild does not have a home set"
            alreadyteleporting: "&9Guilds> &7You are already teleporting"
            movedduringteleport: "&9Guilds> &7Teleportation cancelled, you moved"
            cancelteleportnotinguild: "&9Guilds> &7Teleportation cancelled, you are not in a guild"
            sethomeinclaim: "&9Guilds> &7You must set your home inside of your guild's territory"
            invalidnumberinput: "&9Guilds> &7You must enter a valid number to withdraw"
            withdrawtoomuch: "&9Guilds> &7You cannot withdraw more thank your guild's balance"
            lackfunds: "&9Guilds> &7You lack the funds to deposit that amount"
    team:
        error:
            invalidname: "&9Teams> &7That is an invalid team name"
            inteam: "&9Teams> &7You are already in a team"
            notinteam: "&9Teams> &7You must be in a team to use this command"
            invalidteam: "&9Teams> &7That team does not exist"
            leaveinguild: "&9Teams> &7You cannot leave a team while in a guild"
            invalidcolor: "&9Teams> &7That is not a valid color"
        colorset: "&9Teams> &7Team color sucessfully set"
defaults:
    maxclaimcount: 10
    claimcost: 500
    maxbankamount: 18000
    raidtime: 300
    maxlives: 10
    maxplayersperguild: 20
    guildcreateprice: 1000
    allowfriendlyfire: false
    canseefriendlyinvisibles: true
    backuptime: 600
    invitetime: 300
    tptime: 15